import SwiftUI

struct CandidatePickerView: View {
    let candidates: [SentenceCandidate]
    var onSave: ([SentenceCandidate]) -> Void
    var onCancel: () -> Void
    @Environment(LocalizationStore.self) private var loc

    @State private var editable: [EditableCandidate]
    @State private var selected: Set<UUID>
    @State private var isSaving = false

    init(
        candidates: [SentenceCandidate],
        onSave: @escaping ([SentenceCandidate]) -> Void,
        onCancel: @escaping () -> Void
    ) {
        self.candidates = candidates
        self.onSave = onSave
        self.onCancel = onCancel
        let initial = candidates.map {
            EditableCandidate(id: $0.id, text: $0.text, reading: $0.reading, translation: $0.translation)
        }
        _editable = State(initialValue: initial)
        _selected = State(initialValue: Set(initial.map(\.id)))
    }

    struct EditableCandidate: Identifiable {
        let id: UUID
        var text: String
        var reading: String
        var translation: String
    }

    private func commit() async {
        isSaving = true
        defer { isSaving = false }
        // Reading is already Mecab-generated by the time it reaches this view
        // (OCRPipeline populates it). If the user edited the text line, the
        // displayed reading may now be stale relative to the new text — so
        // regenerate from Mecab in that case (still respecting any manual
        // reading edit by skipping the regen if reading != displayed value).
        var picked: [SentenceCandidate] = []
        for row in editable where selected.contains(row.id)
            && !row.text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            var reading = row.reading
            let originalText = candidates.first(where: { $0.id == row.id })?.text ?? ""
            let textChanged = row.text != originalText
            let readingUntouched = reading == (candidates.first(where: { $0.id == row.id })?.reading ?? "")
            if textChanged && readingUntouched {
                if let regen = try? await JapaneseTokenizer.shared.hiraganaReading(of: row.text),
                   !regen.isEmpty {
                    reading = regen
                }
            }
            let original = candidates.first(where: { $0.id == row.id })
            picked.append(SentenceCandidate(
                text: row.text,
                reading: reading,
                translation: row.translation,
                sourceRegions: original?.sourceRegions ?? []
            ))
        }
        onSave(picked)
    }

    var body: some View {
        List {
            Section {
                ForEach($editable) { $row in
                    HStack(alignment: .top, spacing: 12) {
                        Toggle("", isOn: Binding(
                            get: { selected.contains(row.id) },
                            set: { isOn in
                                if isOn { selected.insert(row.id) } else { selected.remove(row.id) }
                            }
                        ))
                        .labelsHidden()
                        VStack(alignment: .leading, spacing: 6) {
                            TextField(loc.t("candidatePicker.field.original.placeholder"), text: $row.text, axis: .vertical)
                                .font(.body)
                                .textFieldStyle(.plain)
                            TextField(loc.t("candidatePicker.field.reading.placeholder"), text: $row.reading, axis: .vertical)
                                .font(.callout)
                                .foregroundStyle(.secondary)
                                .textFieldStyle(.plain)
                            TextField(loc.t("candidatePicker.field.translation.placeholder"), text: $row.translation, axis: .vertical)
                                .font(.callout)
                                .textFieldStyle(.plain)
                        }
                    }
                    .padding(.vertical, 4)
                }
            } footer: {
                Text(loc.t("candidatePicker.footer"))
            }
        }
        .navigationTitle(loc.t("candidatePicker.title"))
        .navigationBarTitleDisplayMode(.inline)
        .disabled(isSaving)
        .toolbar {
            ToolbarItem(placement: .cancellationAction) {
                Button(loc.t("common.cancel"), role: .cancel) { onCancel() }
            }
            ToolbarItem(placement: .confirmationAction) {
                Button {
                    Task { await commit() }
                } label: {
                    if isSaving { ProgressView() } else { Text(loc.t("common.save")) }
                }
                .disabled(selected.isEmpty || isSaving)
            }
        }
    }
}
